spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
server:
  servlet:
    context-path: /rh/api
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB
      file-size-threshold: 0
      location: ~/temp/

springdoc:
  swagger-ui:
    path: /public/swagger

aws:
  s3:
    bucketName: ${BUCKET_NAME}
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
    region: us-east-1